### ISSUE TITLE
Apply BEM to UserAdmin's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/UserAdmin#22]
This app contains globally applied CSS rules in stylesheets: 
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/css/useradmin.css

It also contains inline CSS in HTML templates: 
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/viewmodels/partials/user/ResetPasswordPage.html
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/viewmodels/partials/administrator/ListUsersPage.html
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/viewmodels/partials/administrator/CreateUserPage.html
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/viewmodels/partials/administrator/EditCompanyPage.html
- https://github.com/StarcounterSamples/UserAdmin/blob/0c03086c24e7ce1548b5c82994721886e08510f9/src/UserAdmin/wwwroot/UserAdmin/viewmodels/partials/administrator/EditUserGroupPage.html

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by diliger** [comment]
PR #65

**Comment by diliger** [comment]
Merged. Closed.
