### ISSUE TITLE
How to use UserAdminApp with other sign in applications?

### ISSUE THREAD

**Issue by miyconst** [StarcounterApps/UserAdmin#3]
Currently UserAdminApp is hard coded:
https://github.com/Polyjuice/UserAdminApp/blob/master/src/Helper.cs#L242

If user tries to access a page which requires login it redirects to `/signinapp/signinuser`.
How to make it work with GoogleSignIn application?

**Comment by andwah** [comment]
:+1:  Im also curious on how to solve this?

**Comment by miyconst** [comment]
@warpech, @andwah I guess there should be a custom block `launcher-account-signin` like `launcher-menu`, `launcher-dashboard` and `launcher-user` then all of the sign in applications should use it same as menu used:

```csharp
Polyjuice.Map("/people/menu", "/polyjuice/menu");
```

I tried to figure out how this works in Launcher, but all of the magic is hidden inside:
```csharp
LauncherHelper.Init();
```

So I can't add my custom block or see how it works.

**Comment by warpech** [comment]
Related: https://github.com/Polyjuice/Launcher/issues/88

**Comment by warpech** [comment]
This pattern is now being explained in https://github.com/Starcounter/Docs/issues/113
