### ISSUE TITLE
Add a new view to register a user

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/UserAdmin#71]
Since we are deleting the [Registration](https://github.com/StarcounterApps/Registration/issues/11) app (https://github.com/StarcounterApps/Registration/issues/11), UserAdmin needs to include a new page for creating users.

Most probably, the view for editing a user can be reused. It should work for users without any permissions. It should include a blending point for Sign In to display the password input.

@PatrykSzwer please take this task. We can discuss the details in person and then add more notes here.

**Comment by PatrykSzwer** [comment]
Actually UserAdmin already contains view of creating new user:
![image](https://cloud.githubusercontent.com/assets/25042256/25843446/a9387c8c-34a7-11e7-9d5a-2f22e8dbf5e1.png)
But with obvious few things to change. As You said, password entry should be taken from SignIn app. Also I Think that we should add field with assigned user group. About that working without any permissions, are you sure about that? Isn't that UserAdmin is app for Admin user only, and shouldn't work for anyone else?

**Comment by PatrykSzwer** [comment]
Done in #72 . Closing.
