### ISSUE TITLE
Apply the new pattern to create MasterPage

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/UserAdmin#74]
A new pattern to create MasterPage was discussed in https://github.com/Starcounter/Guidelines/issues/23 and implemented for reference in https://github.com/StarcounterApps/Website/pull/106.

Please apply the same pattern in UserAdmin app, namely:

- replace `Handle.GET("/useradmin/standalone"` handler with a `GetSessionFromMaster` method
- remove the `GetMaster` method

**Comment by bouguila** [comment]
closing as done.
